# Generated by Django 5.0.1 on 2024-03-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=32)),
                ('images', models.ImageField(default='sample.jpg', upload_to='cat')),
            ],
        ),
    ]
