# Generated by Django 5.0.1 on 2024-03-14 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productcategories',
            new_name='Genres',
        ),
        migrations.RenameField(
            model_name='genres',
            old_name='categories',
            new_name='genre_name',
        ),
    ]
