# Generated by Django 5.0.1 on 2024-03-15 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_rename_productcategories_genres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=120)),
                ('director', models.CharField(max_length=120)),
                ('movie_duration', models.CharField(max_length=120)),
                ('movie_poster', models.ImageField(upload_to='Posters')),
                ('movie_file', models.FileField(upload_to='Movies')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.genres')),
            ],
        ),
    ]
