# Generated by Django 5.0.1 on 2024-03-19 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castname', models.CharField(max_length=24)),
                ('castimage', models.ImageField(upload_to='cast')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.movies')),
            ],
        ),
    ]
