# Generated by Django 5.0.1 on 2024-04-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=34)),
                ('username', models.CharField(max_length=34)),
                ('passward', models.CharField(max_length=34)),
            ],
        ),
    ]
