# Generated by Django 5.0.1 on 2024-04-09 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='passward',
            new_name='password',
        ),
    ]
