# Generated by Django 5.0.1 on 2024-04-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_passward_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phonenumber',
            field=models.CharField(max_length=34, null=True),
        ),
    ]
