# Generated by Django 5.0.1 on 2024-04-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customer_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phonenumber',
            field=models.IntegerField(max_length=34, null=True),
        ),
    ]
