# Generated by Django 5.0.1 on 2024-04-18 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_notification'),
        ('user', '0005_alter_customer_phonenumber_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('films', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.movies')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
            ],
        ),
    ]
