# Generated by Django 5.0.1 on 2024-04-22 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_notification'),
        ('user', '0007_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='movieid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.movies'),
        ),
    ]
