# Generated by Django 5.0.1 on 2024-05-03 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_notification'),
        ('user', '0008_comments_movieid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userlikes', models.IntegerField()),
                ('userdislikes', models.IntegerField()),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.movies')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
            ],
        ),
    ]
