# Generated by Django 5.0.1 on 2024-05-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='userdislikes',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='userlikes',
        ),
    ]
